generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: newman-env
    files:
      - config/newman-dev-env.json
      - config/newman-test-env.json
      - config/newman-prod-env.json

resources:
- source-pvc.yaml
- maven-settings-pvc.yaml
- m2-cache-pvc.yaml
- images-url-pvc.yaml
- server-pipeline.yaml
