apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: server
spec:
  workspaces:
    - name: source
    - name: maven-settings
    - name: images-url
    - name: newman-env
  params:
    - name: source_git_revision
      type: string
      default: master
    - name: source_git_url
      type: string
      default: https://github.com/gnunn-gitops/product-catalog-server
    - name: image_dest_url
      type: string
      description: External registry location for image
      default: quay.io/gnunn/server
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: "$(params.source_git_url)"
        - name: revision
          value: "$(params.source_git_revision)"
        - name: deleteExisting
          value: "true"
    - name: generate-id
      taskRef:
        name: generate-id
        kind: Task
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: source
    - name: build
      taskRef:
        name: maven
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
      runAfter:
        - generate-id
      params:
        - name: GOALS
          value:
            - "package"
    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - build
      params:
      - name: IMAGE
        value: $(params.image_dest_url):$(tasks.generate-id.results.tag_id)
      - name: DOCKERFILE
        value: ./Containerfile        
    - name: dev-tag-image
      taskRef:
        name: skopeo-copy
        kind: ClusterTask
      workspaces:
        - name: images-url
          workspace: images-url
      runAfter:
        - build-image
      params:
        - name: srcImageURL
          value: docker://$(params.image_dest_url)@$(tasks.build-image.results.IMAGE_DIGEST)
        - name: destImageURL
          value: docker://$(params.image_dest_url):dev
    - name: dev-wait-for-update
      taskRef:
        name: argocd-image-updater-wait
      runAfter:
        - dev-tag-image
      params:
        - name: deployment
          value: server
        - name: namespace
          value: demo-dev
        - name: digest
          value: $(tasks.build-image.results.IMAGE_DIGEST)
    - name: dev-automated-tests
      taskRef:
        name: newman
        kind: Task
      runAfter:
        - dev-wait-for-update
      params:
        - name: COLLECTION
          value: $(params.api_test_collection_url)
        - name: ENVIRONMENT
          value: newman-dev-env.json
      workspaces:
        - name: newman-env
          workspace: newman-env