apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
    manifestival: new
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: build-tool
  labels:
    app.kubernetes.io/version: "0.2"
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    operator.tekton.dev/provider-type: redhat
  name: maven
spec:
  description: This Task can be used to run a Maven build.
  params:
  - default: image-registry.openshift-image-registry.svc:5000/openshift/java:latest
    description: Maven base image
    name: MAVEN_IMAGE
    type: string
  - default:
    - package
    description: maven goals to run
    name: GOALS
    type: array
  - default: ""
    description: The Maven repository mirror url
    name: MAVEN_MIRROR_URL
    type: string
  - default: ""
    description: The username for the server
    name: SERVER_USER
    type: string
  - default: ""
    description: The password for the server
    name: SERVER_PASSWORD
    type: string
  - default: ""
    description: The username for the proxy server
    name: PROXY_USER
    type: string
  - default: ""
    description: The password for the proxy server
    name: PROXY_PASSWORD
    type: string
  - default: ""
    description: Port number for the proxy server
    name: PROXY_PORT
    type: string
  - default: ""
    description: Proxy server Host
    name: PROXY_HOST
    type: string
  - default: ""
    description: Non proxy server host
    name: PROXY_NON_PROXY_HOSTS
    type: string
  - default: http
    description: Protocol for the proxy ie http or https
    name: PROXY_PROTOCOL
    type: string
  - default: .
    description: The context directory within the repository for sources on which
      we want to execute maven goals.
    name: CONTEXT_DIR
    type: string
  steps:
  - env:
    - name: HOME
      value: /tekton/home
    image: registry.redhat.io/ubi8/ubi-minimal@sha256:c7b45019f4db32e536e69e102c4028b66bf5cde173cfff4ffd3281ccf7bb3863
    name: mvn-settings
    script: |
      #!/usr/bin/env bash

      [[ -f $(workspaces.maven-settings.path)/settings.xml ]] && \
      echo 'using existing $(workspaces.maven-settings.path)/settings.xml' && exit 0

      cat > $(workspaces.maven-settings.path)/settings.xml <<EOF
      <settings>
        <servers>
          <!-- The servers added here are generated from environment variables. Don't change. -->
          <!-- ### SERVER's USER INFO from ENV ### -->
        </servers>
        <mirrors>
          <!-- The mirrors added here are generated from environment variables. Don't change. -->
          <!-- ### mirrors from ENV ### -->
        </mirrors>
        <proxies>
          <!-- The proxies added here are generated from environment variables. Don't change. -->
          <!-- ### HTTP proxy from ENV ### -->
        </proxies>
      </settings>
      EOF

      xml=""
      if [ -n "$(params.PROXY_HOST)" -a -n "$(params.PROXY_PORT)" ]; then
        xml="<proxy>\
          <id>genproxy</id>\
          <active>true</active>\
          <protocol>$(params.PROXY_PROTOCOL)</protocol>\
          <host>$(params.PROXY_HOST)</host>\
          <port>$(params.PROXY_PORT)</port>"
        if [ -n "$(params.PROXY_USER)" -a -n "$(params.PROXY_PASSWORD)" ]; then
          xml="$xml\
              <username>$(params.PROXY_USER)</username>\
              <password>$(params.PROXY_PASSWORD)</password>"
        fi
        if [ -n "$(params.PROXY_NON_PROXY_HOSTS)" ]; then
          xml="$xml\
              <nonProxyHosts>$(params.PROXY_NON_PROXY_HOSTS)</nonProxyHosts>"
        fi
        xml="$xml\
            </proxy>"
        sed -i "s|<!-- ### HTTP proxy from ENV ### -->|$xml|" $(workspaces.maven-settings.path)/settings.xml
      fi

      if [ -n "$(params.SERVER_USER)" -a -n "$(params.SERVER_PASSWORD)" ]; then
        xml="<server>\
          <id>serverid</id>"
        xml="$xml\
              <username>$(params.SERVER_USER)</username>\
              <password>$(params.SERVER_PASSWORD)</password>"
        xml="$xml\
            </server>"
        sed -i "s|<!-- ### SERVER's USER INFO from ENV ### -->|$xml|" $(workspaces.maven-settings.path)/settings.xml
      fi

      if [ -n "$(params.MAVEN_MIRROR_URL)" ]; then
        xml="    <mirror>\
          <id>mirror.default</id>\
          <url>$(params.MAVEN_MIRROR_URL)</url>\
          <mirrorOf>central</mirrorOf>\
        </mirror>"
        sed -i "s|<!-- ### mirrors from ENV ### -->|$xml|" $(workspaces.maven-settings.path)/settings.xml
      fi
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
  - args:
    - -s
    - $(workspaces.maven-settings.path)/settings.xml
    - $(params.GOALS)
    command:
    - /usr/bin/mvn
    env:
    - name: HOME
      value: /tekton/home
    image: $(params.MAVEN_IMAGE)
    name: mvn-goals
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
    workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
  workspaces:
  - description: The workspace consisting of maven project.
    name: source
  - description: The workspace consisting of the custom maven settings provided by
      the user.
    name: maven-settings
