namespace: demo-prod

resources:
- namespace.yaml
- github.com/gnunn-gitops/product-catalog/components/apps/database/base
- github.com/gnunn-gitops/product-catalog/components/apps/client/base
- github.com/gnunn-gitops/product-catalog/components/apps/server/base