apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Project for production environment
    openshift.io/display-name:  Production
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  name: demo-prod