namespace: demo-dev
resources:
- namespace.yaml
- github.com/gnunn-gitops/product-catalog/components/apps/database/base
- github.com/gnunn-gitops/product-catalog/components/apps/client/base
- github.com/gnunn-gitops/product-catalog/components/apps/server/base
images:
- name: quay.io/gnunn/server
  newName: quay.io/gnunn/server
  newTag: dev
